name: Dockerizer action

on: [push]

jobs:
  build:
    runs-on: openjdk:14.0
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: |
          docker build ./target/*.jar -t 
