name: Dockerizer action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: |
         docker build . -t  projectname:version
      - name: docker login
        env:
         DOCKER_USER: ${{ secrets.DOCKER_USER}} 
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: docker push    
        run: |
          docker push $DOCKER_USER/projectname:version
